### ISSUE TITLE
Unable to find a source package for imagemagick

### ISSUE THREAD

**Issue by dprothero** [talis/imagemagick-deb#1]
When it hits the command `apt-get build-dep imagemagick -y` I'm getting this error. "Unable to find a source package for imagemagick"

**Comment by omarqureshi** [comment]
Interesting, I've managed to replicate it after pulling the latest ubuntu:trusty image

I wonder if they've removed the source repos

Thanks for filing, I'll see about a workaround

**Comment by omarqureshi** [comment]
Looks like modifying sources.list fixes this, will update shortly

**Comment by omarqureshi** [comment]
All fixed. Let me know if you have any other issues and thanks for using this!

**Comment by dprothero** [comment]
Quick turnaround! Nice!
